[r2]
bucketname = vaultwarden-armvps
type = s3
provider = Cloudflare
#env_auth = false
access_key_id = <redacted>
secret_access_key = <redacted>
region = auto
endpoint = https://<redacted>.r2.cloudflarestorage.com
acl = private
# Ref: https://rclone.org/s3/#cloudflare-r2
no_check_bucket = true
